import "./styles.css";

import { useEffect, useState } from "react";



export default function WrapperA(props){

    const [quote, setQuote] = useState("")
    const [author, setAuthor] = useState("")
    const axios = require("axios");

const getQuote = () => {

const options = {
  method: 'GET',
  url: 'https://love-quote.p.rapidapi.com/lovequote',
  headers: {
    'X-RapidAPI-Key': 'b144d81b15msh60fe0177a58a4bap1244ffjsnbc6ee411cd30',
    'X-RapidAPI-Host': 'love-quote.p.rapidapi.com'
  }
};

axios.request(options).then(function (response) {
	console.log(response.data.quote);
    console.log(response.data.author);

    setQuote(response.data.quote);
    setAuthor(response.data.author);
}).catch(function (error) {
	console.error(error);
});

}

useEffect(() => {
  getQuote();
}, []);
//Get quote information and translate it into a tweet
// Get the same random quote generated by the generate love quote button and tweet it
         
    return ( <div id="quote-box">
        <div id="text"><em>"{quote}"</em></div>
        <div id="author"><b>Author:</b> {author}</div>
        <button id="new-quote" onClick={getQuote}><b>Generate Love Quote</b></button>
        <br/>
        <a href={`https://twitter.com/intent/tweet?text=${quote}`} target="_blank" rel="noopener noreferrer"><span id="tweet-quote">Tweet this quote!</span></a>
        </div>
    )
    }